-- TownMart initial database schema for Supabase
-- Run in Supabase SQL Editor after creating a project.
-- Never put the service_role key in the browser or GitHub.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text not null default 'customer' check (role in ('customer','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'Groceries',
  price numeric(10,2) not null check (price >= 0),
  old_price numeric(10,2),
  stock integer not null default 0 check (stock >= 0),
  emoji text not null default '🛍️',
  rating numeric(2,1) not null default 4.5,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references auth.users(id),
  customer_name text not null,
  phone text not null,
  fulfillment text not null default 'pickup' check (fulfillment = 'pickup'),
  utr text not null,
  total numeric(10,2) not null check (total >= 0),
  status text not null default 'PAYMENT_PENDING'
    check (status in ('PAYMENT_PENDING','CONFIRMED','PAYMENT_REJECTED','READY_FOR_PICKUP','COMPLETED','CANCELLED')),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  unit_price numeric(10,2) not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0)
);

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Helper policies check role through the authenticated user's own profile.
create policy "Profiles readable by owner or admin" on public.profiles
  for select to authenticated using (id = auth.uid() or exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  ));
create policy "Products publicly readable" on public.products
  for select to anon, authenticated using (active = true or exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  ));
create policy "Admins insert products" on public.products
  for insert to authenticated with check (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  ));
create policy "Admins update products" on public.products
  for update to authenticated using (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  )) with check (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  ));
create policy "Admins delete products" on public.products
  for delete to authenticated using (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  ));
create policy "Customers create own orders" on public.orders
  for insert to authenticated with check (customer_id = auth.uid());
create policy "Customers read own orders and admins read all" on public.orders
  for select to authenticated using (customer_id = auth.uid() or exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  ));
create policy "Admins update order status" on public.orders
  for update to authenticated using (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  )) with check (exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  ));
create policy "Customers read own order items and admins read all" on public.order_items
  for select to authenticated using (exists (
    select 1 from public.orders o where o.id = order_id and (
      o.customer_id = auth.uid() or exists (
        select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
      )
    )
  ));
create policy "Customers insert items for own orders" on public.order_items
  for insert to authenticated with check (exists (
    select 1 from public.orders o where o.id = order_id and o.customer_id = auth.uid()
  ));

-- IMPORTANT: create the first admin using Supabase Auth, then set role='admin'
-- for that user's UUID in the Supabase SQL Editor. Never allow public role changes.
